NPC Prefab Added
SIG-Game/TheBunkerFell pull request #1
Opened 2024-08-01 01:03 UTC by IsaacS2

NPC prefab added into new NPCScene. Basic following occurs when a player triggers NPC collider. NPC stops following player when too close or when the player has left the NPC's trigger. More sophisticated AI is necessary later so that the NPC will maneuver around walls or other obstacles.

2024-08-14 00:06 UTC, adenprince requested changes
I think an enum type should be used for the NPC state. Other than that, your changes look good to me. I also made some other suggestions that are less important.

2024-08-14 00:06 UTC, adenprince commented on Assets/Scripts/NPC/NPCSensor.cs
> +    public event EventHandler OnPlayerExitSensor;
I think it's simpler to use Actions instead of EventHandlers, but it doesn't matter that much.

2024-08-14 00:06 UTC, adenprince commented on Assets/Scripts/NPC/NPCMovement.cs
> +    private int state = 0;  // idle state
I think an enum type should be used for the NPC state.

2024-08-14 02:42 UTC, IsaacS2 commented on Assets/Scripts/NPC/NPCMovement.cs
> +            Vector3 direction = target.transform.position - transform.position;
I changed it to "directionToPlayer". Might be a bit lengthy but I think it makes sense.

2024-08-14 02:45 UTC, IsaacS2 commented on Assets/Scripts/NPC/NPCMovement.cs
> +        isGrounded = Physics.CheckSphere(groundCheck.position, groundDistance, groundMask);
Sounds good; if gravity is re-implemented later, rigidbodies sound like the way to go.

2024-08-14 02:50 UTC, IsaacS2 commented on Assets/Scripts/NPC/NPCMovement.cs
> +    [SerializeField] float stopDistanceSquared = 2;
I'm not sure why these variables shouldn't have default values, but ok (a brief explanation would be cool, though).

2024-08-20 21:30 UTC, eky2429 commented
I noticed that you added the emunerator, and as far as I could tell. It seems good and the project is working! 👍

2024-08-21 01:02 UTC, merged